services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongo:/data
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${CUSTOMER_DB_NAME}
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - microservices

  postgresql:
    container_name: postgresql_db
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "${POSTGRESQL_DB_PORT}:5432"
    networks:
      - microservices
volumes:
  mongo:
  postgres-data:

networks:
  microservices:
    driver: bridge